# Generated by Django 3.1.2 on 2020-11-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Rubro',
        ),
    ]
