# Generated by Django 3.1.2 on 2020-11-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=60)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
